"""Updated models for authentication

Revision ID: 8c47883d5453
Revises: bb8630fa9bdc
Create Date: 2025-02-22 19:03:27.777331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c47883d5453'
down_revision: Union[str, None] = 'bb8630fa9bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendees_attendee_id', table_name='attendees')
    op.drop_table('attendees')
    op.drop_index('ix_events_event_id', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.INTEGER(), server_default=sa.text("nextval('events_event_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('max_attendees', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('scheduled', 'ongoing', 'completed', 'canceled', name='eventstatus'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('event_id', name='events_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_events_event_id', 'events', ['event_id'], unique=False)
    op.create_table('attendees',
    sa.Column('attendee_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('check_in_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], name='attendees_event_id_fkey'),
    sa.PrimaryKeyConstraint('attendee_id', name='attendees_pkey'),
    sa.UniqueConstraint('email', name='attendees_email_key')
    )
    op.create_index('ix_attendees_attendee_id', 'attendees', ['attendee_id'], unique=False)
    # ### end Alembic commands ###
